CREATE TABLE `trades` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`monthKey` varchar(16) NOT NULL,
	`idx` int NOT NULL,
	`symbol` varchar(32) NOT NULL,
	`direction` enum('BUY','SELL') NOT NULL,
	`lots` double NOT NULL DEFAULT 0,
	`entry` double NOT NULL DEFAULT 0,
	`closePrice` double NOT NULL DEFAULT 0,
	`sl` double,
	`tp` double,
	`tradeR` double,
	`pnl` double NOT NULL DEFAULT 0,
	`swap` double NOT NULL DEFAULT 0,
	`commission` double NOT NULL DEFAULT 0,
	`netPct` double NOT NULL DEFAULT 0,
	`tf` varchar(16) NOT NULL DEFAULT '',
	`chartBefore` text NOT NULL,
	`chartAfter` text NOT NULL,
	`balanceBefore` double NOT NULL DEFAULT 0,
	`balanceAfter` double NOT NULL DEFAULT 0,
	`openStr` varchar(64) NOT NULL DEFAULT '',
	`closeTimeStr` varchar(64) NOT NULL DEFAULT '',
	`day` varchar(16) NOT NULL DEFAULT '',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `trades_id` PRIMARY KEY(`id`),
	CONSTRAINT `uniq_user_month_idx` UNIQUE(`userId`,`monthKey`,`idx`)
);
