import { z } from "zod";
import { protectedProcedure, router } from "./_core/trpc";
import { invokeLLM } from "./_core/llm";

/**
 * Pre-Market Briefing router.
 *
 * Generates a concise, educational daily briefing in Greek. The factual base —
 * the day's high/medium impact economic events — is supplied by the client
 * (sourced from the Market News feed) so the LLM only writes commentary around
 * already-known events and never invents data points. Output is markdown,
 * rendered by <Streamdown> on the client.
 */

const briefingEventSchema = z.object({
  time: z.string().max(32), // pre-formatted local time, e.g. "12:30 UTC"
  currency: z.string().max(8),
  title: z.string().max(160),
  impact: z.enum(["High", "Medium", "Low", "Holiday"]),
  forecast: z.string().max(32).optional().default(""),
  previous: z.string().max(32).optional().default(""),
});

const inputSchema = z.object({
  /** Human-readable date label, e.g. "Παρασκευή 5 Ιουνίου 2026". */
  dateLabel: z.string().max(80),
  events: z.array(briefingEventSchema).max(40),
});

export const briefingRouter = router({
  /**
   * Returns a markdown pre-market briefing for the given day. Falls back to a
   * deterministic markdown skeleton if the LLM is unavailable.
   */
  generate: protectedProcedure
    .input(inputSchema)
    .mutation(async ({ input }) => {
      const fallback = buildFallback(input);

      try {
        const res = await invokeLLM({
          messages: [
            {
              role: "system",
              content: SYSTEM_PROMPT,
            },
            {
              role: "user",
              content: JSON.stringify({
                date: input.dateLabel,
                events: input.events,
              }),
            },
          ],
        });

        const text = res?.choices?.[0]?.message?.content;
        const markdown =
          typeof text === "string" && text.trim().length > 0
            ? text.trim()
            : fallback;
        return {
          markdown,
          source: (markdown === fallback ? "fallback" : "llm") as
            | "llm"
            | "fallback",
          generatedAt: Date.now(),
        };
      } catch {
        return {
          markdown: fallback,
          source: "fallback" as const,
          generatedAt: Date.now(),
        };
      }
    }),
});

const SYSTEM_PROMPT = [
  "Είσαι έμπειρος market analyst που γράφει ένα ημερήσιο Pre-Market Briefing για forex traders.",
  "Γράφεις ΑΥΣΤΗΡΑ στα Ελληνικά, σε επαγγελματικό αλλά καθαρό τόνο, σε μορφή Markdown.",
  "Σου δίνονται η ημερομηνία και τα προγραμματισμένα οικονομικά events της ημέρας (impact, νόμισμα, ώρα, forecast, previous).",
  "ΜΗΝ εφεύρεις νέα οικονομικά στοιχεία ή αριθμούς — σχολίασε μόνο όσα σου δίνονται.",
  "Δομή που ΠΡΕΠΕΙ να ακολουθήσεις ακριβώς (με αυτά τα emoji & επικεφαλίδες):",
  "",
  "## 🌅 Pre-Market Briefing — {ημερομηνία}",
  "",
  "### 📊 Market Sentiment",
  "(2-3 προτάσεις για τη γενική διάθεση της αγοράς, με βάση τα events της ημέρας)",
  "",
  "### 🔴 High Impact Events Today",
  "(bullet list· κάθε γραμμή: **ώρα**: νόμισμα - τίτλος - σύντομο σχόλιο. Αν δεν υπάρχουν high impact, γράψε ότι η ημέρα είναι ήρεμη)",
  "",
  "### 💱 Key Pairs to Watch",
  "(bullet list με 3-4 ζευγάρια π.χ. **EURUSD**: λόγος)",
  "",
  "### 📈 Bias Summary",
  "(Markdown πίνακας με στήλες: Pair | Bias | Reason. Bias = Ανοδικό/Καθοδικό/Ουδέτερο. 3-5 γραμμές)",
  "",
  "### ⚠️ Risk Warnings",
  "(1-2 προτάσεις για τα σημεία αυξημένης μεταβλητότητας/κινδύνου)",
  "",
  "### 💡 Mindset Reminder",
  "(1-2 προτάσεις ψυχολογίας/πειθαρχίας)",
  "",
  "Στο τέλος πρόσθεσε σε πλάγια: *Briefing generated by Ultimate Trading Journal AI | For educational purposes only | Not financial advice*",
].join("\n");

function buildFallback(input: z.infer<typeof inputSchema>): string {
  const high = input.events.filter((e) => e.impact === "High");
  const lines: string[] = [];
  lines.push(`## 🌅 Pre-Market Briefing — ${input.dateLabel}`);
  lines.push("");
  lines.push("### 📊 Market Sentiment");
  lines.push(
    high.length > 0
      ? "Η ημέρα περιλαμβάνει σημαντικές ανακοινώσεις· αναμένεται αυξημένη μεταβλητότητα γύρω από τα high-impact events."
      : "Ήρεμη ημέρα χωρίς high-impact ανακοινώσεις· η αγορά πιθανόν να κινηθεί τεχνικά.",
  );
  lines.push("");
  lines.push("### 🔴 High Impact Events Today");
  if (high.length > 0) {
    for (const e of high) {
      lines.push(
        `- **${e.time}**: ${e.currency} - ${e.title}${
          e.forecast ? ` (forecast ${e.forecast})` : ""
        }`,
      );
    }
  } else {
    lines.push("- Δεν υπάρχουν high-impact events σήμερα.");
  }
  lines.push("");
  lines.push("### 💱 Key Pairs to Watch");
  const currencies = Array.from(
    new Set(high.map((e) => e.currency).filter(Boolean)),
  ).slice(0, 4);
  if (currencies.length > 0) {
    for (const c of currencies) {
      lines.push(`- **${c}**: επηρεάζεται από τις σημερινές ανακοινώσεις.`);
    }
  } else {
    lines.push("- **EURUSD**, **GBPUSD**: παρακολούθηση τεχνικών επιπέδων.");
  }
  lines.push("");
  lines.push("### ⚠️ Risk Warnings");
  lines.push(
    "Προσοχή στην αυξημένη μεταβλητότητα γύρω από τις ανακοινώσεις· χρησιμοποίησε κατάλληλο position sizing.",
  );
  lines.push("");
  lines.push("### 💡 Mindset Reminder");
  lines.push(
    "Επικεντρώσου στη διαχείριση κινδύνου και την τήρηση του πλάνου σου· η συνέπεια μετράει περισσότερο από μία ημέρα.",
  );
  lines.push("");
  lines.push(
    "*Briefing generated by Ultimate Trading Journal AI | For educational purposes only | Not financial advice*",
  );
  return lines.join("\n");
}
