import { z } from "zod";
import { protectedProcedure, router } from "./_core/trpc";
import { invokeLLM } from "./_core/llm";

/**
 * Pre-Market Briefing router.
 *
 * Generates a concise, educational daily briefing in Greek. The factual base —
 * the day's high/medium impact economic events — is supplied by the client
 * (sourced from the Market News feed) so the LLM only writes commentary around
 * already-known events and never invents data points. Output is markdown,
 * rendered by <Streamdown> on the client.
 */

const briefingEventSchema = z.object({
  time: z.string().max(32), // pre-formatted local time, e.g. "12:30 UTC"
  currency: z.string().max(8),
  title: z.string().max(160),
  impact: z.enum(["High", "Medium", "Low", "Holiday"]),
  forecast: z.string().max(32).optional().default(""),
  previous: z.string().max(32).optional().default(""),
});

const inputSchema = z.object({
  /** Human-readable date label, e.g. "Παρασκευή 5 Ιουνίου 2026". */
  dateLabel: z.string().max(80),
  events: z.array(briefingEventSchema).max(40),
  /** UI language; the briefing must be written in this language. Defaults to Greek. */
  lang: z.enum(["en", "el"]).optional(),
});

export const briefingRouter = router({
  /**
   * Returns a markdown pre-market briefing for the given day. Falls back to a
   * deterministic markdown skeleton if the LLM is unavailable.
   */
  generate: protectedProcedure
    .input(inputSchema)
    .mutation(async ({ input }) => {
      const lang = input.lang ?? "el";
      const fallback = buildFallback(input, lang);

      try {
        const res = await invokeLLM({
          messages: [
            {
              role: "system",
              content: lang === "en" ? SYSTEM_PROMPT_EN : SYSTEM_PROMPT,
            },
            {
              role: "user",
              content: JSON.stringify({
                date: input.dateLabel,
                events: input.events,
              }),
            },
          ],
        });

        const text = res?.choices?.[0]?.message?.content;
        const markdown =
          typeof text === "string" && text.trim().length > 0
            ? text.trim()
            : fallback;
        return {
          markdown,
          source: (markdown === fallback ? "fallback" : "llm") as
            | "llm"
            | "fallback",
          generatedAt: Date.now(),
        };
      } catch {
        return {
          markdown: fallback,
          source: "fallback" as const,
          generatedAt: Date.now(),
        };
      }
    }),
});

const SYSTEM_PROMPT = [
  "Είσαι έμπειρος market analyst που γράφει ένα ημερήσιο Pre-Market Briefing για forex traders.",
  "Γράφεις ΑΥΣΤΗΡΑ στα Ελληνικά, σε επαγγελματικό αλλά καθαρό τόνο, σε μορφή Markdown.",
  "Σου δίνονται η ημερομηνία και τα προγραμματισμένα οικονομικά events της ημέρας (impact, νόμισμα, ώρα, forecast, previous).",
  "ΜΗΝ εφεύρεις νέα οικονομικά στοιχεία ή αριθμούς — σχολίασε μόνο όσα σου δίνονται.",
  "Δομή που ΠΡΕΠΕΙ να ακολουθήσεις ακριβώς (με αυτά τα emoji & επικεφαλίδες):",
  "",
  "## 🌅 Pre-Market Briefing — {ημερομηνία}",
  "",
  "### 📊 Market Sentiment",
  "(2-3 προτάσεις για τη γενική διάθεση της αγοράς, με βάση τα events της ημέρας)",
  "",
  "### 🔴 High Impact Events Today",
  "(bullet list· κάθε γραμμή: **ώρα**: νόμισμα - τίτλος - σύντομο σχόλιο. Αν δεν υπάρχουν high impact, γράψε ότι η ημέρα είναι ήρεμη)",
  "",
  "### 💱 Key Pairs to Watch",
  "(bullet list με 3-4 ζευγάρια π.χ. **EURUSD**: λόγος)",
  "",
  "### 📈 Bias Summary",
  "(Markdown πίνακας με στήλες: Pair | Bias | Reason. Bias = Ανοδικό/Καθοδικό/Ουδέτερο. 3-5 γραμμές)",
  "",
  "### ⚠️ Risk Warnings",
  "(1-2 προτάσεις για τα σημεία αυξημένης μεταβλητότητας/κινδύνου)",
  "",
  "### 💡 Mindset Reminder",
  "(1-2 προτάσεις ψυχολογίας/πειθαρχίας)",
  "",
  "Στο τέλος πρόσθεσε σε πλάγια: *Briefing generated by Ultimate Trading Journal AI | For educational purposes only | Not financial advice*",
].join("\n");

const SYSTEM_PROMPT_EN = [
  "You are an experienced market analyst writing a daily Pre-Market Briefing for forex traders.",
  "You write STRICTLY in English, in a professional but clear tone, in Markdown.",
  "You are given the date and the day's scheduled economic events (impact, currency, time, forecast, previous).",
  "Do NOT invent new economic figures or numbers — only comment on what you are given.",
  "Structure you MUST follow exactly (with these emoji & headings):",
  "",
  "## 🌅 Pre-Market Briefing — {date}",
  "",
  "### 📊 Market Sentiment",
  "(2-3 sentences on the general market mood, based on the day's events)",
  "",
  "### 🔴 High Impact Events Today",
  "(bullet list; each line: **time**: currency - title - short comment. If there are no high-impact events, say the day is calm)",
  "",
  "### 💱 Key Pairs to Watch",
  "(bullet list of 3-4 pairs, e.g. **EURUSD**: reason)",
  "",
  "### 📈 Bias Summary",
  "(Markdown table with columns: Pair | Bias | Reason. Bias = Bullish/Bearish/Neutral. 3-5 rows)",
  "",
  "### ⚠️ Risk Warnings",
  "(1-2 sentences on points of elevated volatility/risk)",
  "",
  "### 💡 Mindset Reminder",
  "(1-2 sentences on psychology/discipline)",
  "",
  "At the end add in italics: *Briefing generated by Ultimate Trading Journal AI | For educational purposes only | Not financial advice*",
].join("\n");

function buildFallback(
  input: z.infer<typeof inputSchema>,
  lang: "en" | "el" = "el",
): string {
  const high = input.events.filter((e) => e.impact === "High");
  const en = lang === "en";
  const lines: string[] = [];
  lines.push(`## 🌅 Pre-Market Briefing — ${input.dateLabel}`);
  lines.push("");
  lines.push("### 📊 Market Sentiment");
  lines.push(
    high.length > 0
      ? en
        ? "The day includes significant releases; expect elevated volatility around the high-impact events."
        : "Η ημέρα περιλαμβάνει σημαντικές ανακοινώσεις· αναμένεται αυξημένη μεταβλητότητα γύρω από τα high-impact events."
      : en
        ? "A calm day with no high-impact releases; the market is likely to move technically."
        : "Ήρεμη ημέρα χωρίς high-impact ανακοινώσεις· η αγορά πιθανόν να κινηθεί τεχνικά.",
  );
  lines.push("");
  lines.push("### 🔴 High Impact Events Today");
  if (high.length > 0) {
    for (const e of high) {
      lines.push(
        `- **${e.time}**: ${e.currency} - ${e.title}${
          e.forecast ? ` (forecast ${e.forecast})` : ""
        }`,
      );
    }
  } else {
    lines.push(en ? "- No high-impact events today." : "- Δεν υπάρχουν high-impact events σήμερα.");
  }
  lines.push("");
  lines.push("### 💱 Key Pairs to Watch");
  const currencies = Array.from(
    new Set(high.map((e) => e.currency).filter(Boolean)),
  ).slice(0, 4);
  if (currencies.length > 0) {
    for (const c of currencies) {
      lines.push(
        en
          ? `- **${c}**: affected by today's releases.`
          : `- **${c}**: επηρεάζεται από τις σημερινές ανακοινώσεις.`,
      );
    }
  } else {
    lines.push(
      en
        ? "- **EURUSD**, **GBPUSD**: watch technical levels."
        : "- **EURUSD**, **GBPUSD**: παρακολούθηση τεχνικών επιπέδων.",
    );
  }
  lines.push("");
  lines.push("### ⚠️ Risk Warnings");
  lines.push(
    en
      ? "Beware of elevated volatility around the releases; use appropriate position sizing."
      : "Προσοχή στην αυξημένη μεταβλητότητα γύρω από τις ανακοινώσεις· χρησιμοποίησε κατάλληλο position sizing.",
  );
  lines.push("");
  lines.push("### 💡 Mindset Reminder");
  lines.push(
    en
      ? "Focus on risk management and sticking to your plan; consistency matters more than any single day."
      : "Επικεντρώσου στη διαχείριση κινδύνου και την τήρηση του πλάνου σου· η συνέπεια μετράει περισσότερο από μία ημέρα.",
  );
  lines.push("");
  lines.push(
    "*Briefing generated by Ultimate Trading Journal AI | For educational purposes only | Not financial advice*",
  );
  return lines.join("\n");
}
